export const MOUNTED_LOGIN = "IF/logIn/_LOG_IN_MOUNTED";

export const _POST_LOG_IN_REQUEST = "IF/logIn/_POST_LOG_IN_REQUEST";
export const _POST_LOG_IN_SUCCESS = "IF/logIn/_POST_LOG_IN_SUCCESS";
export const _POST_LOG_IN_FAILURE = "IF/logIn/_POST_LOG_IN_FAILURE";

export const MOUNTED_CHECK_EXIST_TOKEN =
  "IF/logIn/_LOG_IN_MOUNTED_CHECK_EXIST_TOKEN";

export const _POST_CHECK_EXIST_TOKEN_REQUEST =
  "IF/logIn/_POST_CHECK_EXIST_TOKEN_REQUEST";
export const _POST_CHECK_EXIST_TOKEN_SUCCESS =
  "IF/logIn/_POST_CHECK_EXIST_TOKEN_SUCCESS";
export const _POST_CHECK_EXIST_TOKEN_FAILURE =
  "IF/logIn/_POST_CHECK_EXIST_TOKEN_FAILURE";

export const CURRENT_TOKEN = "IF/logIn/_CURRENT_TOKEN";
