export const MOUNTED_ADD_COMMENT = "IF/posts/MOUNTED_ADD_COMMENT";

export const _POST_ADD_COMMENT_REQUEST = "IF/posts/_POST_ADD_COMMENT_REQUEST";
export const _POST_ADD_COMMENT_SUCCESS = "IF/posts/_POST_ADD_COMMENT_SUCCESS";
export const _POST_ADD_COMMENT_FAILURE = "IF/posts/_POST_ADD_COMMENT_FAILURE";
