export const MOUNTED_CONFIRM_ADDRESS_EMAIL =
  "IF/passwordReset/_CONFIRM_ADDRESS_EMAIL_MOUNTED";

export const _POST_CONFIRM_ADDRESS_EMAIL_REQUEST =
  "IF/passwordReset/_POST_CONFIRM_ADDRESS_EMAIL_REQUEST";
export const _POST_CONFIRM_ADDRESS_EMAIL_SUCCESS =
  "IF/passwordReset/_POST_CONFIRM_ADDRESS_EMAIL_SUCCESS";
export const _POST_CONFIRM_ADDRESS_EMAIL_FAILURE =
  "IF/passwordReset/_POST_CONFIRM_ADDRESS_EMAIL_FAILURE";

export const MOUNTED_RESEND_CODE = "IF/passwordReset/_RESEND_CODE_MOUNTED";

export const _POST_RESEND_CODE_REQUEST =
  "IF/passwordReset/_POST_RESEND_CODE_REQUEST";
export const _POST_RESEND_CODE_SUCCESS =
  "IF/passwordReset/_POST_RESEND_CODE_SUCCESS";
export const _POST_RESEND_CODE_FAILURE =
  "IF/passwordReset/_POST_RESEND_CODE_FAILURE";

export const MOUNTED_CHANGE_PASSWORD =
  "IF/passwordReset/_CHANGE_PASSWORD_MOUNTED";

export const _POST_CHANGE_PASSWORD_REQUEST =
  "IF/passwordReset/_POST_CHANGE_PASSWORD_REQUEST";
export const _POST_CHANGE_PASSWORD_SUCCESS =
  "IF/passwordReset/_POST_CHANGE_PASSWORD_SUCCESS";
export const _POST_CHANGE_PASSWORD_FAILURE =
  "IF/passwordReset/_POST_CHANGE_PASSWORD_FAILURE";
