export const MOUNTED = "IF/homePageData/MOUNTED";

export const _GET_HOMEPAGEDATA_REQUEST =
  "IF/homePageData/_GET_HOMEPAGEDATA_REQUEST";
export const _GET_HOMEPAGEDATA_SUCCESS =
  "IF/homePageData/_GET_HOMEPAGEDATA_SUCCESS";
export const _GET_HOMEPAGEDATA_FAILURE =
  "IF/homePageData/_GET_HOMEPAGEDATA_FAILURE";
